name: 'Pull Request another repository'
description: 'Create pull request in another repository'
inputs:
  destination_repo:
    description: 'Destination repository'
    required: true
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_head_branch:
    description: 'The branch to create to push the changes. Cannot be master or main'
    required: true
  destination_base_branch:
    description: 'The branch into which you want your code merged.'
    required: false
    default: "master"
  title:
    description: 'Title of PR'
    required: true
  body:
    description: "Body of PR"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.destination-repo }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.destination-head-branch }}
    - ${{ inputs.destination-base-branch }}
    - ${{ inputs.title }}
    - ${{ inputs.body }}
branding:
  icon: 'git-commit'
  color: 'green'
